### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by 89z** [iamatulsingh/instaDataScrap#6] opened 2021-09-23 22:03 UTC
Using this program:

~~~php
<?php
require_once('insta_data_scrap.class.php');
$username = "britneyspears";
$insta = new InstaData();
$userDetails = $insta->getUserDetails($username);
var_export($userDetails);
~~~

I get this result:

~~~php
'{"img":null,"full_name":null,"username":null,"is_verified":"false","id":null,
"instaUrl":"https:\\/\\/instagram.com\\/"}'
~~~

**Comment by iamatulsingh** [comment] 2021-09-24 02:46
I'm not sure why you are getting that error. I tried reproducing the bug but I'm getting response as expected.

Use your same code:

```
<?php
require_once('insta_data_scrap.class.php');
$username = "britneyspears";
$insta = new InstaData();
$userDetails = $insta->getUserDetails($username);
var_export($userDetails);
```

I got the result
`'{"img":"https:\\/\\/instagram.fknu1-4.fna.fbcdn.net\\/v\\/t51.2885-19\\/s320x320\\/123379409_128889042025206_752561319327172694_n.jpg?_nc_ht=instagram.fknu1-4.fna.fbcdn.net&_nc_ohc=dgoujtR6JREAX9MyPc_&edm=ABfd0MgBAAAA&ccb=7-4&oh=a02651e23026173f8dd7220eb9a8adce&oe=615473D9&_nc_sid=7bff83","full_name":"Britney Spears","username":"britneyspears","is_verified":"true","id":"12246775","instaUrl":"https:\\/\\/instagram.com\\/britneyspears"}'`

**Comment by 89z** [comment] 2021-09-24 02:59
I would try it again, run the code about 16 times, sleep one second between runs. I be surprised if you can make all 16 with no problem.

**Comment by iamatulsingh** [comment] 2021-09-24 03:11
That might give you problem because Insta may detect the scraping.

**Comment by 89z** [comment] 2021-09-24 03:14
Na, Im not going to use a proxy. I will just keep looking for other solution. I am not trying to abuse the system, its only for light personal use.

**Comment by iamatulsingh** [comment] 2021-09-24 03:16
Sure. Let me know for any fix require.

**Comment by 89z** [comment] 2021-09-24 03:17
Thank you for the comments. May peace be with you.

**Comment by iamatulsingh** [comment] 2021-09-24 03:18
You're welcome. You can close the issue if that's not the code issue.

**Closed** 2021-09-24 03:19 UTC
